### PR TITLE
Fix editMember updating of Assignees field

### LINKED ISSUE #232: Updating Member Name which is Assignee of a Task also updates the name of the Assignee

### PR DESCRIPTION
**Pull request by cheeerynne**
- Fix Assignees field for tasks when editMember command is called 
- Made minor edits to command output

### CODE REVIEW

File: src/main/java/seedu/heymatez/logic/commands/FindMembersCommand.java [hunk 1]
```diff
@@ -14,8 +14,8 @@
 
     public static final String COMMAND_WORD = "findMembers";
 
-    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Finds all members whose details contain any of "
-            + "the specified keywords (case-insensitive) and displays them as a list.\n"
+    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Finds all members whose name, phone number, "
```
Comment (zatkiller) [inline src/main/java/seedu/heymatez/logic/commands/FindMembersCommand.java:17]: Should be Find instead of finds? Same for displays?

File: src/main/java/seedu/heymatez/model/HeyMatez.java [hunk 2]
```diff
@@ -149,6 +149,14 @@ public void removeAssignee(Name name) {
         tasks.removeAssignee(name);
     }
 
+    /**
+     * Replaces the given Assignee {@code targetName} with {@code editedName} in tasks from the task list.
```
Comment (zatkiller) [inline src/main/java/seedu/heymatez/model/HeyMatez.java:153]: I think @code refers to the class? Not sure about this

File: src/main/java/seedu/heymatez/model/task/Task.java [hunk 3]
```diff
@@ -106,9 +106,10 @@ public boolean hasAssignee(Assignee assignee) {
 
     /**
      * Returns an updated task with the assignee specified removed from the set of
-     * assignees assignes to this task
-     * @param assignee that is about to be removed
-     * @return Task that is updated without the specified assignee
+     * assignees assignees to this task.
```
Comment (zatkiller) [inline src/main/java/seedu/heymatez/model/task/Task.java]: Typo?

**Review by zatkiller — APPROVED** [review]
Some typos here and there. Also not sure of the @code. Check n change if need to otherwise LGTM

File: src/main/java/seedu/heymatez/model/HeyMatez.java (hunk 2 above)
Comment (cheeerynne) [reply src/main/java/seedu/heymatez/model/HeyMatez.java:153]: @code can refer to the parameter input too

File: src/main/java/seedu/heymatez/model/task/Task.java (hunk 3 above)
Comment (cheeerynne) [reply src/main/java/seedu/heymatez/model/task/Task.java]: Okay fixed
