### PR TITLE
Fix email validation parser

### LINKED ISSUE #206: [PE-D] Email: Syntax accepts domain name of emails with no .com / .org etc.
The syntax of emails can be improved. 
What is considered to be an invalid email address (i.e. no .com .org in the domain) is still valid in the context of the Email field.
Consider improving the syntax being read for email. There are examples online too.
In addition, add max character limits, since long strings can be added.
Nevertheless, good inclusion of mention of alphanumeric characters in error message.

Assuming a Member Alice is added, the following command involving the edit of the email to alice@alice worked:

editMember Alice -e alice@alice -r heead

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Donavanty/ped#9

### PR DESCRIPTION
**Pull request by cheeerynne**

### CODE REVIEW

File: src/test/java/seedu/heymatez/model/person/EmailTest.java [hunk 1]
```diff
@@ -34,7 +34,9 @@ public void isValidEmail() {
         // missing parts
         assertFalse(Email.isValidEmail("@example.com")); // missing local part
         assertFalse(Email.isValidEmail("peterjackexample.com")); // missing '@' symbol
-        assertFalse(Email.isValidEmail("peterjack@")); // missing domain name
+        assertFalse(Email.isValidEmail("peterjack@.com")); // missing domain name
+        assertFalse(Email.isValidEmail("peterjack@examplecom")); // missing '.' symbol for top-level domain
```
Comment (rachelljt) [inline src/test/java/seedu/heymatez/model/person/EmailTest.java]: this is just a personal preference but i think that lines 38, 39 can be swapped so that the email "peterjack@example" can be above "peterjack@examplecom" so that it follows alphabetical ordering!

File: src/main/java/seedu/heymatez/model/person/Email.java [hunk 2]
```diff
@@ -12,21 +12,37 @@
...
+            + "the parentheses, (" + SPECIAL_CHARACTERS + ").\n\n"
+
+            + "3. This is followed by a '@' and then a domain name. "
             + "The domain name must:\n"
-            + "    - be at least 2 characters long\n"
+            + "    - be at least 2 characters long \n"
             + "    - start and end with alphanumeric characters\n"
-            + "    - consist of alphanumeric characters, a period or a hyphen for the characters in between, if any.";
+            + "    - consist of alphanumeric characters, a period or a hyphen for the characters in between, "
+            + "if any.\n\n"
```
Comment (rachelljt) [inline src/main/java/seedu/heymatez/model/person/Email.java:29]: i think it would be better if it the space at the end of line 28 can be brought to line 29 just before "if" so that it is more consistent

**Review by rachelljt — APPROVED** [review]
lgtm! just a few nitpicks

File: src/test/java/seedu/heymatez/model/person/EmailTest.java (hunk 1 above)
Comment (cheeerynne) [reply src/test/java/seedu/heymatez/model/person/EmailTest.java]: Ok, noted

File: src/main/java/seedu/heymatez/model/person/Email.java (hunk 2 above)
Comment (cheeerynne) [reply src/main/java/seedu/heymatez/model/person/Email.java:29]: okay
